project:
  type: website

website:
    search: false
    sidebar:
      style: docked
      logo: assets/logo/logo-dice.png
      logo-alt: "Logo"
      background: "#f9f9f9"
      contents:
      - href: index.qmd
        text: Home
      - href: people.qmd
        text: People
      - href: contents/all-papers.qmd
        text: Publications
      - href: contents/alumni-list.qmd
        text: Alumni
      - href: contents/miscellaneous.qmd
        text: Miscellaneous

          
format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: false # true
    include-in-header:
      # - file: siteimprove.html
      - file: assets/header-includes.html
